version: "3.7"
services:
  click-house-server:
    hostname: db-click-house
    container_name: db-click-house
    restart: always
    image: yandex/clickhouse-server
#    build: ./docker/server

    ports:
      - "8123:8123"
      - "9000:9000"
      - "9005:9005"
      - "9009:9009"
    volumes:
      - data:/var/lib/clickhouse
      - ./configs/config.yml:/etc/clickhouse-server/config.yml
      - ./ssl:/var/ssl/
      - ./configs/users.yaml:/etc/clickhouse-server/users.yaml

      #    network_mode: "host"

#    networks:
#      - click-house

    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144

#    dns_opt:
#      - use-vc
#  client:
#    image: yandex/clickhouse-client
##    build: docker/client
#    depends_on:
#      - click-house-server
#    links:
#      - click-house-server
##    volumes:
##      - ./configs/client-config.xml:/etc/clickhouse-client/config.xml
##    environment:
##      host: db-click-house
##    command: ['--config-file', '/etc/clickhouse-client/config.xml']
#    command: [ '--host', 'db-click-house']
#    networks:
#      - click-house
#    dns_opt:
#      - use-vc

volumes:
  data:
#networks:
#  click-house:
#    driver: bridge
#    name: host
#    external: true

# docker run -it --rm yandex/clickhouse-client --host 192.168.111.66